
// Auth
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const SOCIAL_LOGIN_SUCCESS = "SOCIAL_LOGIN_SUCCESS";
export const SET_TOKEN = "SET_TOKEN";
export const LOGOUT = "LOGOUT";
export const PASSWORD_RESET = "PASSWORD_RESET";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";

// Profile
export const RETRIEVE_PROFILE = "RETRIEVE_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const RETRIEVE_FAIL = "RETRIEVE_FAIL";
export const UPDATE_FAIL = "UPDATE_FAIL";

// notifications
export const GET_ALL_NOTIFICATIONS = "GET_ALL_NOTIFICATIONS";
export const MARK_ALL_NOTIFICATIONS_SEEN = "MARK_ALL_NOTIFICATIONS_SEEN";
export const MARK_ONE_NOTIFICATION_SEEN = "MARK_ONE_NOTIFICATION_SEEN";
export const TOOGLE_NOTIFICATION_PANE = "TOOGLE_NOTIFICATION_PANE";

// errors
export const GET_ERRORS = "GET_ERRORS";

// requests
export const GET_REQUESTS = "GET_REQUESTS";
export const GET_ALL_REQUESTS = "GET_ALL_REQUESTS";
export const REQUEST_ACTION = "REQUEST_ACTION";
