// Auth
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const SOCIAL_LOGIN_SUCCESS = "SOCIAL_LOGIN_SUCCESS";
export const SET_TOKEN = "SET_TOKEN";
export const LOGOUT = "LOGOUT";
export const PASSWORD_RESET = "PASSWORD_RESET";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";

// Profile
export const RETRIEVE_PROFILE = "RETRIEVE_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const RETRIEVE_FAIL = "RETRIEVE_FAIL";
export const UPDATE_FAIL = "UPDATE_FAIL";

// notifications
export const GET_ALL_NOTIFICATIONS = "GET_ALL_NOTIFICATIONS";
export const MARK_ALL_NOTIFICATIONS_SEEN = "MARK_ALL_NOTIFICATIONS_SEEN";
export const MARK_ONE_NOTIFICATION_SEEN = "MARK_ONE_NOTIFICATION_SEEN";
export const TOOGLE_NOTIFICATION_PANE = "TOOGLE_NOTIFICATION_PANE";

// errors
export const GET_ERRORS = "GET_ERRORS";

// requests
export const GET_REQUESTS = "GET_REQUESTS";
export const GET_ALL_REQUESTS = "GET_ALL_REQUESTS";
export const REQUEST_ACTION = "REQUEST_ACTION";
export const GET_PENDING_REQUESTS = "GET_PENDING_REQUESTS";
export const GET_PAST_REQUESTS = "GET_PAST_REQUESTS";
export const CREATE_REQUEST = "CREATE_REQUEST";
export const GET_ALL_ACCOMODATIONS = "GET_ALL_ACCOMODATIONS";
export const GET_ALL_ROOMS = "GET_ALL_ROOMS";

// admin
export const ADD_HOST = "ADD_HOST";

// host
export const RESET_HOST = "RESET_HOST";
// roles
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const ADD_ROLE_FAIL = "ADD_ROLE_FAIL";
export const ROMOVE_ROLE_SUCCESS = "ROMOVE_ROLE_SUCCESS";
export const ROMOVE_ROLE_FAIL = "ROMOVE_ROLE_FAIL";
export const RETRIEVE_USERS_SUCCESS = "RETRIEVE_USERS_SUCCESS";
export const RETRIEVE_USERS_FAIL = "RETRIEVE_USERS_FAIL";
export const CLEAR_STATE = "CLEAR_STATE";
export const CHANGE_AUTO_FILL_SUCCESS = "CHANGE_AUTO_FILL_SUCCESS";
export const CHANGE_AUTO_FILL_FAILED = "CHANGE_AUTO_FILL_FAILED";

// comments
export const SUBMIT_COMMENT = "SUBMIT_COMMENT";
export const SUBMIT_COMMENT_FAIL = "SUBMIT_COMMENT_FAIL";
export const RETRIEVE_COMMENT = "RETRIEVE_COMMENT";
export const RETRIEVE_COMMENT_FAIL = "RETRIEVE_COMMENT_FAIL";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

// accommodation
export const GET_ACCOMODATIONS = "GET_ACCOMODATIONS";
export const GET_ACCOMODATION = "GET_ACCOMODATION";
// trips stats
export const MOST_VISITED = "MOST_VISITED";
export const TRIPS_STATS = "TRIPS_STATS";

// rating
export const RATE = "RATE";
export const GET_RATE = "GET_RATE";

// like & unlike an accommodation
export const LIKE_UNLIKE_ACCOMMODATION = "LIKE_UNLIKE_ACCOMMODATION";
