module.exports = {
  users: {},
  errors: {},
  requests: [],
  accommodations: [],
  accommodation: {},
  notifications: {},
  loginState: {},
  profile: {},
  averageRatings: 0,
  accommodationsLikes: {},
  messages:{},
  locations: [],
  hostAccommodations: [],
  isLoading: false,
  toggleView: false,
};
